/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package project.game.bingo;


import java.util.Random;

import java.util.Arrays;
import java.util.Collections;
import java.util.List;

/**
 *
 * @author aslam
 */
class BingoGUI {
	
}

abstract class BingoController extends BingoGUI {
	BingoBoard[] boards = new BingoBoard[2];
	
	public void startGame() {
		
	}
	public void generateNumber() {
		Integer[] numbers = new Integer[25];
		for (int i = 1; i <= 25; i++) {
			numbers[i - 1] = i;
		}
		List<Integer> numberList = Arrays.asList(numbers);
		Collections.shuffle(numberList);
		numbers = numberList.toArray(new Integer[0]);
	}
}

class BingoBoard {
	Random random = new Random();
	int angka = 1;
	private String playerName;
	private BingoTile[][] tiles = new BingoTile[5][5];
	
	public BingoBoard() {
		playerName = "Player " + angka++;
		Integer[] numbers = new Integer[25];
		for (int i = 1; i <= 25; i++) {
			numbers[i - 1] = i;
		}
		List<Integer> numberList = Arrays.asList(numbers);
		Collections.shuffle(numberList);
		numbers = numberList.toArray(new Integer[0]);
		int pos = 0;
		  
		for (int i = 0; i < 5; i++) {
			for (int j = 0; j < 5; j++) {
				tiles[i][j] = new BingoTile(numbers[pos++]);
			}
		}

	}

	public boolean checkWin() {
		int[] rowCount = new int[5];
		int[] colCount = new int[5];
		int mainDiagonalCount = 0;
		int antiDiagonalCount = 0;
		boolean menang = false;
		for (int i = 0; i < 5; i++) {
			for (int j = 0; j < 5; j++) {
				if (tiles[i][j].marked == true) {			
					rowCount[i]++;
					colCount[j]++;

					if (i == j) mainDiagonalCount++;
					if (i + j == 4) antiDiagonalCount++;

					if (rowCount[i] == 5 || colCount[j] == 5 || mainDiagonalCount == 5 || antiDiagonalCount == 5) {
						menang = true;
					}
				}
			}
		}
		tampilkanBoard();
		if (menang) {
			System.out.println(playerName + " menang");
			return true;
		} else {
			return false;
		}
	}
	
	public void markTile(int number) {
		for (int i = 0; i < 5; i++) {
			for (int j = 0; j < 5; j++) {
				if (tiles[i][j].number == number && !tiles[i][j].marked) {
					tiles[i][j].marked = true;
				}
			}	
		}
		checkWin();
	}
	
	public void tampilkanBoard() {
		for (int i = 0; i < 5; i++) {
			for (int j = 0; j < 5; j++) {
				if (tiles[i][j].marked) {
					System.out.printf("%-5s", "X");
				} else {
					System.out.printf("%-5s", tiles[i][j].getNumber());
				}
			}	
			System.out.println();
		}
	}
	
}

class BingoTile {
	int number;
	boolean marked = false;
	
	public BingoTile(int number) {
		this.number = number;
	}
	
	public int getNumber() {
		return number;
	}
}
public class BingoGameFrame extends javax.swing.JFrame {

    /**
     * Creates new form BingoGameFrame
     */
    public BingoGameFrame() {
        initComponents();
    }

    private Integer[] generateRandomNumbers() {
        Integer[] numbers = new Integer[25];
        for (int i = 1; i <= 25; i++) {
            numbers[i - 1] = i;
        }
        List<Integer> numberList = Arrays.asList(numbers);
        Collections.shuffle(numberList);
        return numberList.toArray(new Integer[0]);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        bingoBoard1 = new javax.swing.JPanel();
        b1tile1 = new javax.swing.JLabel();
        b1tile2 = new javax.swing.JLabel();
        b1tile3 = new javax.swing.JLabel();
        b1tile4 = new javax.swing.JLabel();
        b1tile5 = new javax.swing.JLabel();
        b1tile6 = new javax.swing.JLabel();
        b1tile7 = new javax.swing.JLabel();
        b1tile8 = new javax.swing.JLabel();
        b1tile9 = new javax.swing.JLabel();
        b1tile10 = new javax.swing.JLabel();
        b1tile11 = new javax.swing.JLabel();
        b1tile12 = new javax.swing.JLabel();
        b1tile13 = new javax.swing.JLabel();
        b1tile14 = new javax.swing.JLabel();
        b1tile15 = new javax.swing.JLabel();
        b1tile16 = new javax.swing.JLabel();
        b1tile17 = new javax.swing.JLabel();
        b1tile18 = new javax.swing.JLabel();
        b1tile19 = new javax.swing.JLabel();
        b1tile20 = new javax.swing.JLabel();
        b1tile21 = new javax.swing.JLabel();
        b1tile22 = new javax.swing.JLabel();
        b1tile23 = new javax.swing.JLabel();
        b1tile24 = new javax.swing.JLabel();
        b1tile25 = new javax.swing.JLabel();
        bingoBoard2 = new javax.swing.JPanel();
        b2tile1 = new javax.swing.JLabel();
        b2tile2 = new javax.swing.JLabel();
        b2tile3 = new javax.swing.JLabel();
        b2tile4 = new javax.swing.JLabel();
        b2tile5 = new javax.swing.JLabel();
        b2tile6 = new javax.swing.JLabel();
        b2tile7 = new javax.swing.JLabel();
        b2tile8 = new javax.swing.JLabel();
        b2tile9 = new javax.swing.JLabel();
        b2tile10 = new javax.swing.JLabel();
        b2tile11 = new javax.swing.JLabel();
        b2tile12 = new javax.swing.JLabel();
        b2tile13 = new javax.swing.JLabel();
        b2tile14 = new javax.swing.JLabel();
        b2tile15 = new javax.swing.JLabel();
        b2tile16 = new javax.swing.JLabel();
        b2tile17 = new javax.swing.JLabel();
        b2tile18 = new javax.swing.JLabel();
        b2tile19 = new javax.swing.JLabel();
        b2tile20 = new javax.swing.JLabel();
        b2tile21 = new javax.swing.JLabel();
        b2tile22 = new javax.swing.JLabel();
        b2tile23 = new javax.swing.JLabel();
        b2tile24 = new javax.swing.JLabel();
        b2tile25 = new javax.swing.JLabel();
        player1Panel = new javax.swing.JPanel();
        player1Name = new javax.swing.JLabel();
        p1Wins = new javax.swing.JTextField();
        player2Panel = new javax.swing.JPanel();
        player2Name = new javax.swing.JLabel();
        p2Wins = new javax.swing.JTextField();
        btnStart = new javax.swing.JButton();
        gameInfoPanel = new javax.swing.JPanel();
        lblCurrentNumber = new javax.swing.JLabel();
        lblCurrentTurn = new javax.swing.JLabel();
        lblcurrentRound = new javax.swing.JLabel();
        CurrentNumberField = new javax.swing.JTextField();
        CurrentTurnField = new javax.swing.JTextField();
        CurrentRoundField = new javax.swing.JTextField();
        btnExit = new javax.swing.JButton();
        gameLogPanel = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        GameLogField = new javax.swing.JTextArea();
        GameLogLabel = new javax.swing.JLabel();
        btnGenerateNumber = new javax.swing.JButton();

        jTextArea3.setColumns(20);
        jTextArea3.setRows(5);
        jScrollPane2.setViewportView(jTextArea3);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bingoBoard1.setBackground(new java.awt.Color(255, 255, 255));
        bingoBoard1.setToolTipText("");
        bingoBoard1.setLayout(new java.awt.GridLayout(5, 5));

        b1tile1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b1tile1.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, java.awt.Color.lightGray));
        bingoBoard1.add(b1tile1);

        b1tile2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b1tile2.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, java.awt.Color.lightGray));
        bingoBoard1.add(b1tile2);

        b1tile3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b1tile3.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, java.awt.Color.lightGray));
        bingoBoard1.add(b1tile3);

        b1tile4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b1tile4.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, java.awt.Color.lightGray));
        bingoBoard1.add(b1tile4);

        b1tile5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b1tile5.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, java.awt.Color.lightGray));
        bingoBoard1.add(b1tile5);

        b1tile6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b1tile6.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, java.awt.Color.lightGray));
        bingoBoard1.add(b1tile6);

        b1tile7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b1tile7.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, java.awt.Color.lightGray));
        bingoBoard1.add(b1tile7);

        b1tile8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b1tile8.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, java.awt.Color.lightGray));
        bingoBoard1.add(b1tile8);

        b1tile9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b1tile9.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, java.awt.Color.lightGray));
        bingoBoard1.add(b1tile9);

        b1tile10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b1tile10.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, java.awt.Color.lightGray));
        bingoBoard1.add(b1tile10);

        b1tile11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b1tile11.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, java.awt.Color.lightGray));
        bingoBoard1.add(b1tile11);

        b1tile12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b1tile12.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, java.awt.Color.lightGray));
        bingoBoard1.add(b1tile12);

        b1tile13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b1tile13.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, java.awt.Color.lightGray));
        bingoBoard1.add(b1tile13);

        b1tile14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b1tile14.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, java.awt.Color.lightGray));
        bingoBoard1.add(b1tile14);

        b1tile15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b1tile15.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, java.awt.Color.lightGray));
        bingoBoard1.add(b1tile15);

        b1tile16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b1tile16.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, java.awt.Color.lightGray));
        bingoBoard1.add(b1tile16);

        b1tile17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b1tile17.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, java.awt.Color.lightGray));
        bingoBoard1.add(b1tile17);

        b1tile18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b1tile18.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, java.awt.Color.lightGray));
        bingoBoard1.add(b1tile18);

        b1tile19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b1tile19.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, java.awt.Color.lightGray));
        bingoBoard1.add(b1tile19);

        b1tile20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b1tile20.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, java.awt.Color.lightGray));
        bingoBoard1.add(b1tile20);

        b1tile21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b1tile21.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, java.awt.Color.lightGray));
        bingoBoard1.add(b1tile21);

        b1tile22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b1tile22.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, java.awt.Color.lightGray));
        bingoBoard1.add(b1tile22);

        b1tile23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b1tile23.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, java.awt.Color.lightGray));
        bingoBoard1.add(b1tile23);

        b1tile24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b1tile24.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, java.awt.Color.lightGray));
        bingoBoard1.add(b1tile24);

        b1tile25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b1tile25.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, java.awt.Color.lightGray));
        bingoBoard1.add(b1tile25);

        bingoBoard2.setBackground(new java.awt.Color(255, 255, 255));
        bingoBoard2.setLayout(new java.awt.GridLayout(5, 5));

        b2tile1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b2tile1.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray));
        bingoBoard2.add(b2tile1);

        b2tile2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b2tile2.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray));
        bingoBoard2.add(b2tile2);

        b2tile3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b2tile3.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray));
        bingoBoard2.add(b2tile3);

        b2tile4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b2tile4.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray));
        bingoBoard2.add(b2tile4);

        b2tile5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b2tile5.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray));
        bingoBoard2.add(b2tile5);

        b2tile6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b2tile6.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray));
        bingoBoard2.add(b2tile6);

        b2tile7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b2tile7.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray));
        bingoBoard2.add(b2tile7);

        b2tile8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b2tile8.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray));
        bingoBoard2.add(b2tile8);

        b2tile9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b2tile9.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray));
        bingoBoard2.add(b2tile9);

        b2tile10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b2tile10.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray));
        bingoBoard2.add(b2tile10);

        b2tile11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b2tile11.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray));
        bingoBoard2.add(b2tile11);

        b2tile12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b2tile12.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray));
        bingoBoard2.add(b2tile12);

        b2tile13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b2tile13.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray));
        bingoBoard2.add(b2tile13);

        b2tile14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b2tile14.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray));
        bingoBoard2.add(b2tile14);

        b2tile15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b2tile15.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray));
        bingoBoard2.add(b2tile15);

        b2tile16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b2tile16.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray));
        bingoBoard2.add(b2tile16);

        b2tile17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b2tile17.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray));
        bingoBoard2.add(b2tile17);

        b2tile18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b2tile18.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray));
        bingoBoard2.add(b2tile18);

        b2tile19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b2tile19.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray));
        bingoBoard2.add(b2tile19);

        b2tile20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b2tile20.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray));
        bingoBoard2.add(b2tile20);

        b2tile21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b2tile21.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray));
        bingoBoard2.add(b2tile21);

        b2tile22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b2tile22.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray));
        bingoBoard2.add(b2tile22);

        b2tile23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b2tile23.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray));
        bingoBoard2.add(b2tile23);

        b2tile24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b2tile24.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray));
        bingoBoard2.add(b2tile24);

        b2tile25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b2tile25.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray));
        bingoBoard2.add(b2tile25);

        player1Panel.setBackground(new java.awt.Color(204, 255, 255));

        player1Name.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        player1Name.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        player1Name.setText("Player 1");

        p1Wins.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        p1Wins.setText("Wins: 0");

        javax.swing.GroupLayout player1PanelLayout = new javax.swing.GroupLayout(player1Panel);
        player1Panel.setLayout(player1PanelLayout);
        player1PanelLayout.setHorizontalGroup(
            player1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(player1Name, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(player1PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(p1Wins, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                .addContainerGap())
        );
        player1PanelLayout.setVerticalGroup(
            player1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(player1PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(player1Name)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(p1Wins, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        player2Panel.setBackground(new java.awt.Color(204, 255, 255));

        player2Name.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        player2Name.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        player2Name.setText("Player 2");

        p2Wins.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        p2Wins.setText("Wins: 0");

        javax.swing.GroupLayout player2PanelLayout = new javax.swing.GroupLayout(player2Panel);
        player2Panel.setLayout(player2PanelLayout);
        player2PanelLayout.setHorizontalGroup(
            player2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(player2Name, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(player2PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(p2Wins, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                .addContainerGap())
        );
        player2PanelLayout.setVerticalGroup(
            player2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(player2PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(player2Name)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(p2Wins, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        btnStart.setText("Start Game");
        btnStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartActionPerformed(evt);
            }
        });

        gameInfoPanel.setBackground(new java.awt.Color(204, 255, 255));

        lblCurrentNumber.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCurrentNumber.setText("Current Number:");

        lblCurrentTurn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCurrentTurn.setText("Current Turn:");

        lblcurrentRound.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblcurrentRound.setText("Current Round:");

        CurrentNumberField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        CurrentNumberField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        CurrentNumberField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CurrentNumberFieldActionPerformed(evt);
            }
        });

        CurrentTurnField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        CurrentTurnField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CurrentTurnFieldActionPerformed(evt);
            }
        });

        CurrentRoundField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout gameInfoPanelLayout = new javax.swing.GroupLayout(gameInfoPanel);
        gameInfoPanel.setLayout(gameInfoPanelLayout);
        gameInfoPanelLayout.setHorizontalGroup(
            gameInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gameInfoPanelLayout.createSequentialGroup()
                .addGroup(gameInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCurrentNumber, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                    .addGroup(gameInfoPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblcurrentRound, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(gameInfoPanelLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(CurrentNumberField))
                    .addComponent(lblCurrentTurn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(gameInfoPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(CurrentTurnField))
                    .addGroup(gameInfoPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(CurrentRoundField)))
                .addContainerGap())
        );
        gameInfoPanelLayout.setVerticalGroup(
            gameInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gameInfoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCurrentNumber)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CurrentNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblCurrentTurn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CurrentTurnField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblcurrentRound)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CurrentRoundField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 18, Short.MAX_VALUE))
        );

        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        GameLogField.setColumns(20);
        GameLogField.setRows(5);
        jScrollPane4.setViewportView(GameLogField);

        GameLogLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        GameLogLabel.setText("Game Log");

        javax.swing.GroupLayout gameLogPanelLayout = new javax.swing.GroupLayout(gameLogPanel);
        gameLogPanel.setLayout(gameLogPanelLayout);
        gameLogPanelLayout.setHorizontalGroup(
            gameLogPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, gameLogPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(GameLogLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        gameLogPanelLayout.setVerticalGroup(
            gameLogPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, gameLogPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(GameLogLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE))
        );

        btnGenerateNumber.setText("Generate Number");
        btnGenerateNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerateNumberActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(player1Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(386, 386, 386)
                .addComponent(player2Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(bingoBoard1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(gameInfoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnStart)
                            .addComponent(btnGenerateNumber)
                            .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(gameLogPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bingoBoard2, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(player1Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gameInfoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnStart)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnGenerateNumber)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnExit)
                        .addGap(21, 21, 21)
                        .addComponent(player2Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bingoBoard1, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                    .addComponent(bingoBoard2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(gameLogPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartActionPerformed

       //Membuka tab baru meminta input "Berapa round yang ingin dimainkan" 
       //tile board 1
Integer[] tile1 = generateRandomNumbers();
b1tile1.setText(tile1[0].toString());
b1tile2.setText(tile1[1].toString());
b1tile3.setText(tile1[2].toString());
b1tile4.setText(tile1[3].toString());
b1tile5.setText(tile1[4].toString());
b1tile6.setText(tile1[5].toString());
b1tile7.setText(tile1[6].toString());
b1tile8.setText(tile1[7].toString());
b1tile9.setText(tile1[8].toString());
b1tile10.setText(tile1[9].toString());
b1tile11.setText(tile1[10].toString());
b1tile12.setText(tile1[11].toString());
b1tile13.setText(tile1[12].toString());
b1tile14.setText(tile1[13].toString());
b1tile15.setText(tile1[14].toString());
b1tile16.setText(tile1[15].toString());
b1tile17.setText(tile1[16].toString());
b1tile18.setText(tile1[17].toString());
b1tile19.setText(tile1[18].toString());
b1tile20.setText(tile1[19].toString());
b1tile21.setText(tile1[20].toString());
b1tile22.setText(tile1[21].toString());
b1tile23.setText(tile1[22].toString());
b1tile24.setText(tile1[23].toString());
b1tile25.setText(tile1[24].toString());

       //tile board 2
        Integer[] tile2 = generateRandomNumbers();
        b2tile1.setText(tile2[0].toString());
        b2tile2.setText(tile2[1].toString());
        b2tile3.setText(tile2[2].toString());
        b2tile4.setText(tile2[3].toString());
        b2tile5.setText(tile2[4].toString());
        b2tile6.setText(tile2[5].toString());
        b2tile7.setText(tile2[6].toString());
        b2tile8.setText(tile2[7].toString());
        b2tile9.setText(tile2[8].toString());
        b2tile10.setText(tile2[9].toString());
        b2tile11.setText(tile2[10].toString());
        b2tile12.setText(tile2[11].toString());
        b2tile13.setText(tile2[12].toString());
        b2tile14.setText(tile2[13].toString());
        b2tile15.setText(tile2[14].toString());
        b2tile16.setText(tile2[15].toString());
        b2tile17.setText(tile2[16].toString());
        b2tile18.setText(tile2[17].toString());
        b2tile19.setText(tile2[18].toString());
        b2tile20.setText(tile2[19].toString());
        b2tile21.setText(tile2[20].toString());
        b2tile22.setText(tile2[21].toString());
        b2tile23.setText(tile2[22].toString());
        b2tile24.setText(tile2[23].toString());
        b2tile25.setText(tile2[24].toString());
        // TODO add your handling code here:

    }//GEN-LAST:event_btnStartActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // Keluar program
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnGenerateNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerateNumberActionPerformed
        // Memgenerate angka baru kemudian mengecek angka dari board jika sama maka di coret
        Integer [] CurrentNumber = generateRandomNumbers();
        CurrentNumberField.setText(CurrentNumber[0].toString());
       
        //if(CurrentNumber==)

    }//GEN-LAST:event_btnGenerateNumberActionPerformed

    private void b1tile1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1tile1ActionPerformed
        // TODO add your handling code here:
        b1tile1.setText("X");
    }//GEN-LAST:event_b1tile1ActionPerformed

    private void b1tile2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1tile2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b1tile2ActionPerformed

    private void b1tile3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1tile3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b1tile3ActionPerformed

    private void b1tile4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1tile4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b1tile4ActionPerformed

    private void CurrentTurnFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CurrentTurnFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CurrentTurnFieldActionPerformed

    private void CurrentNumberFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CurrentNumberFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CurrentNumberFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BingoGameFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BingoGameFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BingoGameFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BingoGameFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BingoGameFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CurrentNumberField;
    private javax.swing.JTextField CurrentRoundField;
    private javax.swing.JTextField CurrentTurnField;
    private javax.swing.JTextArea GameLogField;
    private javax.swing.JLabel GameLogLabel;
    private javax.swing.JLabel b1tile1;
    private javax.swing.JLabel b1tile10;
    private javax.swing.JLabel b1tile11;
    private javax.swing.JLabel b1tile12;
    private javax.swing.JLabel b1tile13;
    private javax.swing.JLabel b1tile14;
    private javax.swing.JLabel b1tile15;
    private javax.swing.JLabel b1tile16;
    private javax.swing.JLabel b1tile17;
    private javax.swing.JLabel b1tile18;
    private javax.swing.JLabel b1tile19;
    private javax.swing.JLabel b1tile2;
    private javax.swing.JLabel b1tile20;
    private javax.swing.JLabel b1tile21;
    private javax.swing.JLabel b1tile22;
    private javax.swing.JLabel b1tile23;
    private javax.swing.JLabel b1tile24;
    private javax.swing.JLabel b1tile25;
    private javax.swing.JLabel b1tile3;
    private javax.swing.JLabel b1tile4;
    private javax.swing.JLabel b1tile5;
    private javax.swing.JLabel b1tile6;
    private javax.swing.JLabel b1tile7;
    private javax.swing.JLabel b1tile8;
    private javax.swing.JLabel b1tile9;
    private javax.swing.JLabel b2tile1;
    private javax.swing.JLabel b2tile10;
    private javax.swing.JLabel b2tile11;
    private javax.swing.JLabel b2tile12;
    private javax.swing.JLabel b2tile13;
    private javax.swing.JLabel b2tile14;
    private javax.swing.JLabel b2tile15;
    private javax.swing.JLabel b2tile16;
    private javax.swing.JLabel b2tile17;
    private javax.swing.JLabel b2tile18;
    private javax.swing.JLabel b2tile19;
    private javax.swing.JLabel b2tile2;
    private javax.swing.JLabel b2tile20;
    private javax.swing.JLabel b2tile21;
    private javax.swing.JLabel b2tile22;
    private javax.swing.JLabel b2tile23;
    private javax.swing.JLabel b2tile24;
    private javax.swing.JLabel b2tile25;
    private javax.swing.JLabel b2tile3;
    private javax.swing.JLabel b2tile4;
    private javax.swing.JLabel b2tile5;
    private javax.swing.JLabel b2tile6;
    private javax.swing.JLabel b2tile7;
    private javax.swing.JLabel b2tile8;
    private javax.swing.JLabel b2tile9;
    private javax.swing.JPanel bingoBoard1;
    private javax.swing.JPanel bingoBoard2;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnGenerateNumber;
    private javax.swing.JButton btnStart;
    private javax.swing.JPanel gameInfoPanel;
    private javax.swing.JPanel gameLogPanel;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JLabel lblCurrentNumber;
    private javax.swing.JLabel lblCurrentTurn;
    private javax.swing.JLabel lblcurrentRound;
    private javax.swing.JTextField p1Wins;
    private javax.swing.JTextField p2Wins;
    private javax.swing.JLabel player1Name;
    private javax.swing.JPanel player1Panel;
    private javax.swing.JLabel player2Name;
    private javax.swing.JPanel player2Panel;
    // End of variables declaration//GEN-END:variables
}
//  if (TileNumber == currentGeneratedNumber) {
//         b1tile1.setText("B"); // Atau huruf "B", atau warna, terserah
//         
//     } else {
//         b1tile1.setText(String.valueOf(TileNumber)); // tampilkan angka normal
//     }