/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package project.game.bingo;

/**
 *
 * @author aslam
 */
public class BingoGameFrame extends javax.swing.JFrame {

    /**
     * Creates new form BingoGameFrame
     */
    public BingoGameFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bingoBoard1 = new javax.swing.JPanel();
        b1tile1 = new javax.swing.JButton();
        b1tile2 = new javax.swing.JButton();
        b1tile3 = new javax.swing.JButton();
        b1tile4 = new javax.swing.JButton();
        b1tile5 = new javax.swing.JButton();
        b1tile6 = new javax.swing.JButton();
        b1tile7 = new javax.swing.JButton();
        b1tile8 = new javax.swing.JButton();
        b1tile9 = new javax.swing.JButton();
        b1tile10 = new javax.swing.JButton();
        b1tile11 = new javax.swing.JButton();
        b1tile13 = new javax.swing.JButton();
        b1tile12 = new javax.swing.JButton();
        b1tile14 = new javax.swing.JButton();
        b1tile15 = new javax.swing.JButton();
        b1tile16 = new javax.swing.JButton();
        b1tile17 = new javax.swing.JButton();
        b1tile18 = new javax.swing.JButton();
        b1tile19 = new javax.swing.JButton();
        b1tile20 = new javax.swing.JButton();
        b1tile21 = new javax.swing.JButton();
        b1tile22 = new javax.swing.JButton();
        b1tile23 = new javax.swing.JButton();
        b1tile24 = new javax.swing.JButton();
        b1tile25 = new javax.swing.JButton();
        bingoBoard2 = new javax.swing.JPanel();
        b2tile1 = new javax.swing.JLabel();
        b2tile2 = new javax.swing.JLabel();
        b2tile3 = new javax.swing.JLabel();
        b2tile4 = new javax.swing.JLabel();
        b2tile5 = new javax.swing.JLabel();
        b2tile6 = new javax.swing.JLabel();
        b2tile7 = new javax.swing.JLabel();
        b2tile8 = new javax.swing.JLabel();
        b2tile9 = new javax.swing.JLabel();
        b2tile10 = new javax.swing.JLabel();
        b2tile11 = new javax.swing.JLabel();
        b2tile12 = new javax.swing.JLabel();
        b2tile13 = new javax.swing.JLabel();
        b2tile14 = new javax.swing.JLabel();
        b2tile15 = new javax.swing.JLabel();
        b2tile16 = new javax.swing.JLabel();
        b2tile17 = new javax.swing.JLabel();
        b2tile18 = new javax.swing.JLabel();
        b2tile19 = new javax.swing.JLabel();
        b2tile20 = new javax.swing.JLabel();
        b2tile21 = new javax.swing.JLabel();
        b2tile22 = new javax.swing.JLabel();
        b2tile23 = new javax.swing.JLabel();
        b2tile24 = new javax.swing.JLabel();
        b2tile25 = new javax.swing.JLabel();
        playerInfo1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        playerInfo2 = new javax.swing.JLabel();
        btnStart = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        currentNumber = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        currentTurn = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        btnNextTurn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bingoBoard1.setToolTipText("");
        bingoBoard1.setLayout(new java.awt.GridLayout(5, 5));
        bingoBoard1.add(b1tile1);
        bingoBoard1.add(b1tile2);
        bingoBoard1.add(b1tile3);
        bingoBoard1.add(b1tile4);

        b1tile5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1tile5ActionPerformed(evt);
            }
        });
        bingoBoard1.add(b1tile5);

        b1tile6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1tile6ActionPerformed(evt);
            }
        });
        bingoBoard1.add(b1tile6);

        b1tile7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1tile7ActionPerformed(evt);
            }
        });
        bingoBoard1.add(b1tile7);

        b1tile8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1tile8ActionPerformed(evt);
            }
        });
        bingoBoard1.add(b1tile8);

        b1tile9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1tile9ActionPerformed(evt);
            }
        });
        bingoBoard1.add(b1tile9);

        b1tile10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1tile10ActionPerformed(evt);
            }
        });
        bingoBoard1.add(b1tile10);

        b1tile11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1tile11ActionPerformed(evt);
            }
        });
        bingoBoard1.add(b1tile11);

        b1tile13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1tile13ActionPerformed(evt);
            }
        });
        bingoBoard1.add(b1tile13);

        b1tile12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1tile12ActionPerformed(evt);
            }
        });
        bingoBoard1.add(b1tile12);

        b1tile14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1tile14ActionPerformed(evt);
            }
        });
        bingoBoard1.add(b1tile14);

        b1tile15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1tile15ActionPerformed(evt);
            }
        });
        bingoBoard1.add(b1tile15);

        b1tile16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1tile16ActionPerformed(evt);
            }
        });
        bingoBoard1.add(b1tile16);

        b1tile17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1tile17ActionPerformed(evt);
            }
        });
        bingoBoard1.add(b1tile17);

        b1tile18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1tile18ActionPerformed(evt);
            }
        });
        bingoBoard1.add(b1tile18);

        b1tile19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1tile19ActionPerformed(evt);
            }
        });
        bingoBoard1.add(b1tile19);

        b1tile20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1tile20ActionPerformed(evt);
            }
        });
        bingoBoard1.add(b1tile20);

        b1tile21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1tile21ActionPerformed(evt);
            }
        });
        bingoBoard1.add(b1tile21);

        b1tile22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1tile22ActionPerformed(evt);
            }
        });
        bingoBoard1.add(b1tile22);

        b1tile23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1tile23ActionPerformed(evt);
            }
        });
        bingoBoard1.add(b1tile23);

        b1tile24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1tile24ActionPerformed(evt);
            }
        });
        bingoBoard1.add(b1tile24);

        b1tile25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1tile25ActionPerformed(evt);
            }
        });
        bingoBoard1.add(b1tile25);

        bingoBoard2.setBackground(new java.awt.Color(255, 255, 255));
        bingoBoard2.setLayout(new java.awt.GridLayout(5, 5));

        b2tile1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b2tile1.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray));
        bingoBoard2.add(b2tile1);

        b2tile2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b2tile2.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray));
        bingoBoard2.add(b2tile2);

        b2tile3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b2tile3.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray));
        bingoBoard2.add(b2tile3);

        b2tile4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b2tile4.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray));
        bingoBoard2.add(b2tile4);

        b2tile5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b2tile5.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray));
        bingoBoard2.add(b2tile5);

        b2tile6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b2tile6.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray));
        bingoBoard2.add(b2tile6);

        b2tile7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b2tile7.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray));
        bingoBoard2.add(b2tile7);

        b2tile8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b2tile8.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray));
        bingoBoard2.add(b2tile8);

        b2tile9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b2tile9.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray));
        bingoBoard2.add(b2tile9);

        b2tile10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b2tile10.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray));
        bingoBoard2.add(b2tile10);

        b2tile11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b2tile11.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray));
        bingoBoard2.add(b2tile11);

        b2tile12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b2tile12.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray));
        bingoBoard2.add(b2tile12);

        b2tile13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b2tile13.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray));
        bingoBoard2.add(b2tile13);

        b2tile14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b2tile14.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray));
        bingoBoard2.add(b2tile14);

        b2tile15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b2tile15.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray));
        bingoBoard2.add(b2tile15);

        b2tile16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b2tile16.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray));
        bingoBoard2.add(b2tile16);

        b2tile17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b2tile17.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray));
        bingoBoard2.add(b2tile17);

        b2tile18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b2tile18.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray));
        bingoBoard2.add(b2tile18);

        b2tile19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b2tile19.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray));
        bingoBoard2.add(b2tile19);

        b2tile20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b2tile20.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray));
        bingoBoard2.add(b2tile20);

        b2tile21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b2tile21.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray));
        bingoBoard2.add(b2tile21);

        b2tile22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b2tile22.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray));
        bingoBoard2.add(b2tile22);

        b2tile23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b2tile23.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray));
        bingoBoard2.add(b2tile23);

        b2tile24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b2tile24.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray));
        bingoBoard2.add(b2tile24);

        b2tile25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b2tile25.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray));
        bingoBoard2.add(b2tile25);

        playerInfo1.setBackground(new java.awt.Color(204, 255, 255));

        jLabel1.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Player 1");

        javax.swing.GroupLayout playerInfo1Layout = new javax.swing.GroupLayout(playerInfo1);
        playerInfo1.setLayout(playerInfo1Layout);
        playerInfo1Layout.setHorizontalGroup(
            playerInfo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
        );
        playerInfo1Layout.setVerticalGroup(
            playerInfo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(playerInfo1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(56, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(204, 255, 255));

        playerInfo2.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        playerInfo2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        playerInfo2.setText("Player 2");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(playerInfo2, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(playerInfo2)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        btnStart.setText("Start Game");
        btnStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Current Number:");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        currentNumber.setViewportView(jTextArea1);

        currentTurn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        currentTurn.setText("Current Turn:");

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane1.setViewportView(jTextArea2);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(currentTurn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(currentNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(currentNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(currentTurn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 8, Short.MAX_VALUE))
        );

        btnNextTurn.setText("Exit");
        btnNextTurn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextTurnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bingoBoard1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(playerInfo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnStart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnNextTurn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(38, 38, 38)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(bingoBoard2, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(138, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(playerInfo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(bingoBoard2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bingoBoard1, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(btnStart)
                        .addGap(79, 79, 79)
                        .addComponent(btnNextTurn))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b1tile5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1tile5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b1tile5ActionPerformed

    private void b1tile6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1tile6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b1tile6ActionPerformed

    private void b1tile7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1tile7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b1tile7ActionPerformed

    private void b1tile8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1tile8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b1tile8ActionPerformed

    private void b1tile9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1tile9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b1tile9ActionPerformed

    private void b1tile10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1tile10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b1tile10ActionPerformed

    private void b1tile11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1tile11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b1tile11ActionPerformed

    private void b1tile12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1tile12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b1tile12ActionPerformed

    private void b1tile13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1tile13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b1tile13ActionPerformed

    private void b1tile14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1tile14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b1tile14ActionPerformed

    private void b1tile15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1tile15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b1tile15ActionPerformed

    private void b1tile16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1tile16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b1tile16ActionPerformed

    private void b1tile17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1tile17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b1tile17ActionPerformed

    private void b1tile18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1tile18ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b1tile18ActionPerformed

    private void b1tile19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1tile19ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b1tile19ActionPerformed

    private void b1tile20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1tile20ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b1tile20ActionPerformed

    private void b1tile21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1tile21ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b1tile21ActionPerformed

    private void b1tile22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1tile22ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b1tile22ActionPerformed

    private void b1tile23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1tile23ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b1tile23ActionPerformed

    private void b1tile24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1tile24ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b1tile24ActionPerformed

    private void b1tile25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1tile25ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b1tile25ActionPerformed

    private void btnStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnStartActionPerformed

    private void btnNextTurnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextTurnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNextTurnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BingoGameFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BingoGameFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BingoGameFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BingoGameFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BingoGameFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b1tile1;
    private javax.swing.JButton b1tile10;
    private javax.swing.JButton b1tile11;
    private javax.swing.JButton b1tile12;
    private javax.swing.JButton b1tile13;
    private javax.swing.JButton b1tile14;
    private javax.swing.JButton b1tile15;
    private javax.swing.JButton b1tile16;
    private javax.swing.JButton b1tile17;
    private javax.swing.JButton b1tile18;
    private javax.swing.JButton b1tile19;
    private javax.swing.JButton b1tile2;
    private javax.swing.JButton b1tile20;
    private javax.swing.JButton b1tile21;
    private javax.swing.JButton b1tile22;
    private javax.swing.JButton b1tile23;
    private javax.swing.JButton b1tile24;
    private javax.swing.JButton b1tile25;
    private javax.swing.JButton b1tile3;
    private javax.swing.JButton b1tile4;
    private javax.swing.JButton b1tile5;
    private javax.swing.JButton b1tile6;
    private javax.swing.JButton b1tile7;
    private javax.swing.JButton b1tile8;
    private javax.swing.JButton b1tile9;
    private javax.swing.JLabel b2tile1;
    private javax.swing.JLabel b2tile10;
    private javax.swing.JLabel b2tile11;
    private javax.swing.JLabel b2tile12;
    private javax.swing.JLabel b2tile13;
    private javax.swing.JLabel b2tile14;
    private javax.swing.JLabel b2tile15;
    private javax.swing.JLabel b2tile16;
    private javax.swing.JLabel b2tile17;
    private javax.swing.JLabel b2tile18;
    private javax.swing.JLabel b2tile19;
    private javax.swing.JLabel b2tile2;
    private javax.swing.JLabel b2tile20;
    private javax.swing.JLabel b2tile21;
    private javax.swing.JLabel b2tile22;
    private javax.swing.JLabel b2tile23;
    private javax.swing.JLabel b2tile24;
    private javax.swing.JLabel b2tile25;
    private javax.swing.JLabel b2tile3;
    private javax.swing.JLabel b2tile4;
    private javax.swing.JLabel b2tile5;
    private javax.swing.JLabel b2tile6;
    private javax.swing.JLabel b2tile7;
    private javax.swing.JLabel b2tile8;
    private javax.swing.JLabel b2tile9;
    private javax.swing.JPanel bingoBoard1;
    private javax.swing.JPanel bingoBoard2;
    private javax.swing.JButton btnNextTurn;
    private javax.swing.JButton btnStart;
    private javax.swing.JScrollPane currentNumber;
    private javax.swing.JLabel currentTurn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JPanel playerInfo1;
    private javax.swing.JLabel playerInfo2;
    // End of variables declaration//GEN-END:variables
}
